[env:qtpy_esp32s3]
platform = espressif32@6.7.0
board = adafruit_qtpy_esp32s3_n4r2
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.0
  adafruit/Adafruit SSD1306 @ ^2.5.0
